version: '3.3'

services:
  backend_server:
    build: ../backend
    command: uvicorn src.asgi:app --host 0.0.0.0 --port 8000
    container_name: application_server
    ports:
      - 8000:8000
    environment:
      MONGO_URI: $MONGO_URI

  frontend_build_service:
    build: ../frontend
    command: npm run build
    container_name: frontend_build
    volumes:
      - /var/www/frontend/dist:/app/dist

  reverse_proxy:
    image: nginx:1.21.6
    container_name: nginx_proxy
    volumes:
      - /var/www/frontend/dist:/var/www/
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 80:80
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=80
    depends_on:
      - backend_server

  mongodb:
    image: mongo:7.0.2
    container_name: mongodb
    volumes:
      - mongodb_data:/data/db
    env_file:
      - .env.example
    ports:
      - 27017:27017

  redis:
    image: redis:alpine
    restart: always
    ports:
      - 6379:6379

  rabbitmq:
    image: 'rabbitmq:3.6-management-alpine'
    ports:
      - '5672:5672'
      - '15672:15672'

volumes:
  mongodb_data:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/db_data
      o: bind