name: Docker Compose CI

on:
  push:
    branches:
      - main

jobs:
  build-front:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: RUN
        run: cd infrastructure && docker compose -f ./docker-compose.yml up --build frontend_build_service


  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: RUN
        run: cd infrastructure && docker compose -f ./docker-compose.yml up --build backend_server reverse_proxy